export interface BibleBook {
  name: string;      // Nome PT-BR exibido na interface
  apiName: string;   // Nome EN usado na bible-api.com
  chapters: number;  // Número total de capítulos
  testament: 'AT' | 'NT';
}

export const BIBLE_BOOKS: BibleBook[] = [
  // Antigo Testamento
  { name: 'Gênesis', apiName: 'genesis', chapters: 50, testament: 'AT' },
  { name: 'Êxodo', apiName: 'exodus', chapters: 40, testament: 'AT' },
  { name: 'Levítico', apiName: 'leviticus', chapters: 27, testament: 'AT' },
  { name: 'Números', apiName: 'numbers', chapters: 36, testament: 'AT' },
  { name: 'Deuteronômio', apiName: 'deuteronomy', chapters: 34, testament: 'AT' },
  { name: 'Josué', apiName: 'joshua', chapters: 24, testament: 'AT' },
  { name: 'Juízes', apiName: 'judges', chapters: 21, testament: 'AT' },
  { name: 'Rute', apiName: 'ruth', chapters: 4, testament: 'AT' },
  { name: '1 Samuel', apiName: '1 samuel', chapters: 31, testament: 'AT' },
  { name: '2 Samuel', apiName: '2 samuel', chapters: 24, testament: 'AT' },
  { name: '1 Reis', apiName: '1 kings', chapters: 22, testament: 'AT' },
  { name: '2 Reis', apiName: '2 kings', chapters: 25, testament: 'AT' },
  { name: '1 Crônicas', apiName: '1 chronicles', chapters: 29, testament: 'AT' },
  { name: '2 Crônicas', apiName: '2 chronicles', chapters: 36, testament: 'AT' },
  { name: 'Esdras', apiName: 'ezra', chapters: 10, testament: 'AT' },
  { name: 'Neemias', apiName: 'nehemiah', chapters: 13, testament: 'AT' },
  { name: 'Ester', apiName: 'esther', chapters: 10, testament: 'AT' },
  { name: 'Jó', apiName: 'job', chapters: 42, testament: 'AT' },
  { name: 'Salmos', apiName: 'psalms', chapters: 150, testament: 'AT' },
  { name: 'Provérbios', apiName: 'proverbs', chapters: 31, testament: 'AT' },
  { name: 'Eclesiastes', apiName: 'ecclesiastes', chapters: 12, testament: 'AT' },
  { name: 'Cantares', apiName: 'song of solomon', chapters: 8, testament: 'AT' },
  { name: 'Isaías', apiName: 'isaiah', chapters: 66, testament: 'AT' },
  { name: 'Jeremias', apiName: 'jeremiah', chapters: 52, testament: 'AT' },
  { name: 'Lamentações', apiName: 'lamentations', chapters: 5, testament: 'AT' },
  { name: 'Ezequiel', apiName: 'ezekiel', chapters: 48, testament: 'AT' },
  { name: 'Daniel', apiName: 'daniel', chapters: 12, testament: 'AT' },
  { name: 'Oséias', apiName: 'hosea', chapters: 14, testament: 'AT' },
  { name: 'Joel', apiName: 'joel', chapters: 3, testament: 'AT' },
  { name: 'Amós', apiName: 'amos', chapters: 9, testament: 'AT' },
  { name: 'Obadias', apiName: 'obadiah', chapters: 1, testament: 'AT' },
  { name: 'Jonas', apiName: 'jonah', chapters: 4, testament: 'AT' },
  { name: 'Miquéias', apiName: 'micah', chapters: 7, testament: 'AT' },
  { name: 'Naum', apiName: 'nahum', chapters: 3, testament: 'AT' },
  { name: 'Habacuque', apiName: 'habakkuk', chapters: 3, testament: 'AT' },
  { name: 'Sofonias', apiName: 'zephaniah', chapters: 3, testament: 'AT' },
  { name: 'Ageu', apiName: 'haggai', chapters: 2, testament: 'AT' },
  { name: 'Zacarias', apiName: 'zechariah', chapters: 14, testament: 'AT' },
  { name: 'Malaquias', apiName: 'malachi', chapters: 4, testament: 'AT' },
  
  // Novo Testamento
  { name: 'Mateus', apiName: 'matthew', chapters: 28, testament: 'NT' },
  { name: 'Marcos', apiName: 'mark', chapters: 16, testament: 'NT' },
  { name: 'Lucas', apiName: 'luke', chapters: 24, testament: 'NT' },
  { name: 'João', apiName: 'john', chapters: 21, testament: 'NT' },
  { name: 'Atos', apiName: 'acts', chapters: 28, testament: 'NT' },
  { name: 'Romanos', apiName: 'romans', chapters: 16, testament: 'NT' },
  { name: '1 Coríntios', apiName: '1 corinthians', chapters: 16, testament: 'NT' },
  { name: '2 Coríntios', apiName: '2 corinthians', chapters: 13, testament: 'NT' },
  { name: 'Gálatas', apiName: 'galatians', chapters: 6, testament: 'NT' },
  { name: 'Efésios', apiName: 'ephesians', chapters: 6, testament: 'NT' },
  { name: 'Filipenses', apiName: 'philippians', chapters: 4, testament: 'NT' },
  { name: 'Colossenses', apiName: 'colossians', chapters: 4, testament: 'NT' },
  { name: '1 Tessalonicenses', apiName: '1 thessalonians', chapters: 5, testament: 'NT' },
  { name: '2 Tessalonicenses', apiName: '2 thessalonians', chapters: 3, testament: 'NT' },
  { name: '1 Timóteo', apiName: '1 timothy', chapters: 6, testament: 'NT' },
  { name: '2 Timóteo', apiName: '2 timothy', chapters: 4, testament: 'NT' },
  { name: 'Tito', apiName: 'titus', chapters: 3, testament: 'NT' },
  { name: 'Filemom', apiName: 'philemon', chapters: 1, testament: 'NT' },
  { name: 'Hebreus', apiName: 'hebrews', chapters: 13, testament: 'NT' },
  { name: 'Tiago', apiName: 'james', chapters: 5, testament: 'NT' },
  { name: '1 Pedro', apiName: '1 peter', chapters: 5, testament: 'NT' },
  { name: '2 Pedro', apiName: '2 peter', chapters: 3, testament: 'NT' },
  { name: '1 João', apiName: '1 john', chapters: 5, testament: 'NT' },
  { name: '2 João', apiName: '2 john', chapters: 1, testament: 'NT' },
  { name: '3 João', apiName: '3 john', chapters: 1, testament: 'NT' },
  { name: 'Judas', apiName: 'jude', chapters: 1, testament: 'NT' },
  { name: 'Apocalipse', apiName: 'revelation', chapters: 22, testament: 'NT' },
];
